[tools]
btop = "latest"
dotnet = "latest"
fastfetch = "latest"
lazygit = "latest"
neovim = "latest"
node = "latest"
"npm:@qwen-code/qwen-code" = "latest"
ripgrep = "latest"
starship = "latest"
zoxide = "latest"
